# Site settings
title: Elisa Maria Wirsching
# general_email: your_general_email@gmail.com
academic_email: e.m.wirsching@lse.ac.uk

description: > # this means to ignore newlines until "baseurl:"
  Assistant Professor, London School of Economics

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://ElisaWirsching.github.io" # the base hostname & protocol for your site

twitter_username: elisawirsching
github_username: ElisaWirsching
linkedin_username: elisa-wirsching-847a36128
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

url: "https://ElisaWirsching.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap